-- Rituraj Link Manager / Supabase schema
-- Run this once in Supabase SQL Editor.

create table if not exists public.profile (
  id integer primary key,
  display_name text not null default 'Rituraj',
  username text not null default '@yourusername',
  bio text not null default 'Connect with me 👋',
  avatar_url text not null default 'https://i.pravatar.cc/300?img=12',
  updated_at timestamptz not null default now()
);

insert into public.profile (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.links (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text not null default '',
  url text not null,
  icon text not null default 'link',
  enabled boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profile enable row level security;
alter table public.links enable row level security;

-- Public page: anyone can read profile and enabled links.
drop policy if exists "public read profile" on public.profile;
create policy "public read profile"
on public.profile for select
to anon, authenticated
using (true);

drop policy if exists "public read enabled links" on public.links;
create policy "public read enabled links"
on public.links for select
to anon, authenticated
using (enabled = true);

-- Admin: authenticated user can manage everything.
drop policy if exists "auth manage profile" on public.profile;
create policy "auth manage profile"
on public.profile for all
to authenticated
using (true)
with check (true);

drop policy if exists "auth manage links" on public.links;
create policy "auth manage links"
on public.links for all
to authenticated
using (true)
with check (true);

-- Recommended: create ONE admin user in Supabase Authentication.
-- Do not put your password in this SQL file.
